[Feature] Add vote music integration
PFilip08/elektron-radio-player pull request #16
Opened 2024-12-06 20:11 UTC by PFilip08

2024-12-06 23:20 UTC, Zaptyp requested changes
Drobne rzeczy do poprawki :3

2024-12-06 23:20 UTC, Zaptyp commented on api/controllers/votes.controller.js
> +        logger('verbose', 'Wystąpił błąd podczas usuwania głosu', 'LocalAPI - setVotes');
```suggestion
        logger('verbose', 'Wystąpił błąd podczas usuwania głosu', 'LocalAPI - delVotes');
```
Coś się panu zapomniało zmienić

2024-12-06 23:20 UTC, Zaptyp commented on api/controllers/votes.controller.js
> +            DebugSaveToFile('LocalAPI', 'setVotes', 'catched_error', e);
Tu tak samo

2024-12-06 23:20 UTC, Zaptyp commented on api/controllers/votes.controller.js
> +            logger('verbose', `Stacktrace został zrzucony do debug/`, 'LocalAPI - setVotes');
I tu też

2024-12-06 23:20 UTC, Zaptyp commented on api/controllers/votes.controller.js
> +        res.status(500).send('Wystąpił błąd serwera');
Brak returna

2024-12-06 23:20 UTC, Zaptyp commented on api/controllers/votes.controller.js
> +                logger('task', `Usunięto ${files[i]}`, 'delmp3')
Brak średnika

2024-12-06 23:20 UTC, Zaptyp commented on api/controllers/votes.controller.js
> +            logger('log', 'Brak danych!!!', 'download')
Brak średnika

2024-12-06 23:20 UTC, Zaptyp commented on api/controllers/votes.controller.js
> +                logger('task', `Usunięto ${files[i]}`, 'saveVotes')
Brak średnika

2024-12-06 23:20 UTC, Zaptyp commented on api/controllers/votes.controller.js
> +                    fs.rmSync('./mp3/7/'+files[i], { recursive: true, force: true })
Brak średnika

2024-12-06 23:20 UTC, Zaptyp commented on modules/MusicDownloader.js
> +        logger('verbose', 'Wykryto próbę pobrania piosenki nie piosenki w głosach!', 'downloader');
Dziwnie to brzmi do poprawy
Proponuje: 
```suggestion
        logger('verbose', 'Wykryto próbę pobrania nie piosenki w głosach!', 'downloader');
```
(Tak wiem że sam to pisałem)

2024-12-06 23:20 UTC, Zaptyp commented on modules/MusicDownloader.js
> +            DebugSaveToFile('MusicDownloader', 'downloadSong', 'error_main_function', e);
Zmień nazwę error_main_function na catched_error
```suggestion
            DebugSaveToFile('MusicDownloader', 'downloadSong', 'catched_error', e);
```

2024-12-06 23:20 UTC, Zaptyp commented on modules/MusicDownloader.js
> +            let song = await getTrackInfo(data.tracks[i])
Stary brak średnika

2024-12-06 23:20 UTC, Zaptyp commented on modules/MusicDownloader.js
> +            let song = await getTrackInfo(data.tracks[i])
Stary brak średnika

2024-12-06 23:20 UTC, Zaptyp commented on modules/MusicDownloader.js
> +        logger('error', "Błąd w trakcie wykonywania funkcji downloadSong", 'downloadPlaylist');
No właśnie co tu nie pasuje?

2024-12-06 23:20 UTC, Zaptyp commented on modules/MusicDownloader.js
> +            DebugSaveToFile('MusicDownloader', 'downloadPlaylist', 'error_main_function', e);
Zmień z error_main_function na catched_error
```suggestion
            DebugSaveToFile('MusicDownloader', 'downloadPlaylist', 'catched_error', e);
```

2024-12-06 23:20 UTC, Zaptyp commented on modules/MusicDownloader.js
> +            let song = await getTrackInfo(data.tracks[i])
Stary brak średnika

2024-12-06 23:20 UTC, Zaptyp commented on modules/MusicDownloader.js
> +        logger('error', "Błąd w trakcie wykonywania funkcji downloadSong", 'downloadAlbum');
No właśnie co tu jest nie tak z tym logiem?

2024-12-06 23:20 UTC, Zaptyp commented on modules/MusicDownloader.js
> +            DebugSaveToFile('MusicDownloader', 'downloadAlbum', 'error_main_function', e);
Zmień error_main_function na catched_error
```suggestion
            DebugSaveToFile('MusicDownloader', 'downloadAlbum', 'catched_error', e);
```

2024-12-06 23:20 UTC, Zaptyp commented on modules/MusicDownloader.js
> +        logger('error', "Błąd w trakcie wykonywania funkcji downloadSong", 'getTrackInfo');
No właśnie co tu jest nie tak z tym logiem?

2024-12-06 23:20 UTC, Zaptyp commented on modules/MusicDownloader.js
> +            DebugSaveToFile('MusicDownloader', 'getTrackInfo', 'error_main_function', e);
Zmień error_main_function na catched_error
```suggestion
            DebugSaveToFile('MusicDownloader', 'getTrackInfo', 'catched_error', e);
```

2024-12-06 23:20 UTC, Zaptyp commented on modules/MusicDownloader.js
> +            logger('task', `Usunięto ${files[i]}`, 'autoRemoveFiles')
Brak średnika

2024-12-06 23:20 UTC, Zaptyp commented on modules/MusicDownloader.js
> +                fs.rmSync('./mp3/7/'+files[i], { recursive: true, force: true })
Brak średnika

2024-12-06 23:20 UTC, Zaptyp commented on modules/MusicPlayer.js
> +const vlc = `cvlc -I http --http-host 127.0.0.1 --http-port ${process.env.VLC_PORT || 4212} --http-password ${process.env.VLC_PASSWORD} --one-instance`
Brak średnika (No chyba że dla consta nie można)

2024-12-06 23:20 UTC, Zaptyp commented on modules/MusicPlayer.js
> +                new Error('Czas wykonania funkcji przekroczony')
Brak średnika

2024-12-06 23:20 UTC, Zaptyp commented on modules/TaskScheduler.js
> +        logger('error', `Dla zasady ${rule} i przerwy ${breakNumberInt}, czas zakończenia (${timeEnd} aka "end" w JSONie) jest wcześniejszy niż czas rozpoczęcia (${timeStart}), różnica wynosi ${(time
Brak średnika

2024-12-06 23:20 UTC, Zaptyp commented on modules/TaskScheduler.js
> +            logger('error', `Dla zasady ${rule} i przerwy ${breakNumberInt}, czas zakończenia (${timeEnd} aka "end" w JSONie) jest wcześniejszy niż czas rozpoczęcia (${timeStart} aka "start" w JSONie
Brak średnika

2024-12-06 23:20 UTC, Zaptyp commented on modules/TaskScheduler.js
> +            logger('error', `Dla zasady ${rule} i przerwy ${breakNumberInt}, czas zakończenia (${timeEnd} aka "end" w JSONie) jest taki sam jak czas rozpoczęcia (${timeStart} aka "start" w JSONie).`,
Brak średnika

2024-12-06 23:20 UTC, Zaptyp commented on modules/TaskScheduler.js
> +        return logger('error','Brakuje danych!!!', 'massSchedule')
Brak średnika

2024-12-06 23:20 UTC, Zaptyp commented on modules/VotesConnector.js
> +export const votesPath = './mp3/Votes.json'
Brak średnika

2024-12-06 23:20 UTC, Zaptyp commented on modules/VotesConnector.js
> +    date=date.toLocaleDateString('en-CA') // YYYY-MM-DD
Brak średnika

2024-12-06 23:20 UTC, Zaptyp commented on api/controllers/votes.controller.js
> +        fs.readdir('./mp3/7', (err, files) => {
Czemu raz używamy z Syncem a raz bez?
Jak jest jakieś techniczne wytłumaczenie to nie ma problemu aby tak zostało :3

2024-12-07 10:13 UTC, PFilip08 commented on modules/MusicPlayer.js
> +                new Error('Czas wykonania funkcji przekroczony')
tam ma ne być

2024-12-07 12:21 UTC, Zaptyp approved these changes
LGTM!

2024-12-07 18:13 UTC, merged